set(camaro_files
	Common/Common.cpp
	Common/Common.h
	Common/ProjectDefines.h
	Common/String.h
	Game/Instances/Bunny.cpp
	Game/Instances/Bunny.h
	Game/Instances/Dynamic.cpp
	Game/Instances/Dynamic.h
	Game/Instances/Instance.h
	Game/Instances/InstanceProperties.h
	Game/Instances/Solid.cpp
	Game/Instances/Solid.h
	Game/Instances/TestObject.cpp
	Game/Instances/TestObject.h
	Game/InstanceManager.cpp
	Game/InstanceManager.h
	Game/World.cpp
	Game/World.h
	Input/DX/DXGamepadInput.cpp
	Input/DX/DXGamepadInput.h
	Input/DX/DXKeyboardInput.cpp
	Input/DX/DXKeyboardInput.h
	Input/InputDevice.h
	Input/InputManager.cpp
	Input/InputManager.h	
	Launcher/Main.cpp
	Physics/Physics.cpp
	Physics/Physics.h
	Physics/PhysicsCommon.h
	Physics/PhysicsModifier.cpp
	Physics/PhysicsModifier.h
	Physics/PhysicsProxy.cpp
	Physics/PhysicsProxy.h
	Physics/PhysicsRenderer.cpp
	Physics/PhysicsRenderer.h
	Renderer/DX/DXDebugRenderer.cpp
	Renderer/DX/DXDebugRenderer.h
	Renderer/DX/DXRenderer.cpp
	Renderer/DX/DXRenderer.h
	Renderer/DX/DXRenderProxy.cpp
	Renderer/DX/DXRenderProxy.h
	Renderer/DX/DXRenderQueue.cpp
	Renderer/DX/DXRenderQueue.h
	Renderer/Renderer.h
	System/Memory/MemoryAllocator.cpp
	System/Memory/MemoryAllocator.h
	System/Threading/Thread.cpp
	System/Threading/Thread.h
	System/Clock.cpp
	System/Clock.h
	System/God.cpp
	System/God.h
	System/Log.cpp
	System/Log.h
)